DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS day;
DROP TABLE IF EXISTS discovered_days;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE day (
  id INTEGER PRIMARY KEY,
  day_no INTEGER NOT NULL,
  quest TEXT,
  quest_answer TEXT
);

CREATE TABLE discovered_days (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  day_id INTEGER NOT NULL,
  user_id INTEGER NOT NULL,
  FOREIGN KEY (day_id) REFERENCES day (id),
  FOREIGN KEY (user_id) REFERENCES user (id)
);