name: publish

on:
  push:
    branches:    
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      
    - name: scp files
      uses: garygrossgarten/github-action-scp@release
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        privateKey: ${{ secrets.KEY }}
        local: "/home/runner/work/AdventCalendar.2019/AdventCalendar.2019"
        remote: ${{ secrets.DEST_PATH }}
        
    - name: restart web server
      uses: garygrossgarten/github-action-ssh@v0.3.0
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        privateKey: ${{ secrets.KEY }}
        command: ${{ secrets.RESTART }}
